#ifndef __CONFIG__CONFIG_H__
#define __CONFIG__CONFIG_H__

#define FRAMEWORK_VERSION "0.1"
#define FRAMEWORK_COMMIT "@GIT_COMMIT_HASH"
#define FRAMEWORK_EXPERIMENTAL true

#endif // __CONFIG__CONFIG_H__